import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import tseslint from 'typescript-eslint'
import prettier from 'eslint-config-prettier/flat'

export default defineConfig([
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'dist/**',
    'next-env.d.ts',
    // generated by `pnpm typegen`
    'sanity.types.ts',
    'schema.json'
  ]),

  // Next.js + React + React Hooks + jsx-a11y + import (official flat config)
  ...nextVitals,

  // Type-aware TypeScript linting at the strictest level — source files only
  {
    files: ['**/*.{ts,tsx}'],
    extends: [tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname
      }
    },
    rules: {
      // Allow `_`-prefixed intentionally-unused vars/args
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
      ],
      // `void fn()` is the escape hatch for deliberately-unawaited promises (no-floating-promises is on via strictTypeChecked)
      '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: { attributes: false } }],
      // strictTypeChecked forbids ALL non-string template exprs; numbers/booleans are fine
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true, allowBoolean: true }],
      // Force a `default`/exhaustive handling of every union member — catches missed cases when a union grows
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      // Keep type-only imports separate so they're fully erased at build time
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }]
    }
  },

  // Project-wide preferences
  {
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-param-reassign': ['error', { props: true }],
      'object-shorthand': 'warn'
    }
  },

  // Prettier handles all formatting — keep last so it wins
  prettier
])
