/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  bio?: string
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  linkedinUrl?: string
  githubUrl?: string
}

export type Sidenote = {
  _type: 'sidenote'
  text?: string
}

export type PullQuote = {
  _type: 'pullQuote'
  text?: string
}

export type Latex = {
  _id: string
  _type: 'latex'
  _createdAt: string
  _updatedAt: string
  _rev: string
  latex_string?: string
}

export type External = {
  _id: string
  _type: 'external'
  _createdAt: string
  _updatedAt: string
  _rev: string
  link_to_html?: string
  width?: number
  height?: number
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  color?: number
}

export type Tech = {
  _id: string
  _type: 'tech'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  description?: string
  logo_image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  tech_page?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Duration = {
  _type: 'duration'
  start?: string
  end?: string
}

export type Education = {
  _id: string
  _type: 'education'
  _createdAt: string
  _updatedAt: string
  _rev: string
  school?: string
  degree?: string
  year_start?: number
  year_end?: number
  company?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'company'
  }
}

export type Experience = {
  _id: string
  _type: 'experience'
  _createdAt: string
  _updatedAt: string
  _rev: string
  company?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'company'
  }
  role?: string
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  featured?: boolean
  duration?: Duration
  description?: BlockContent
  technologies?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tech'
  }>
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & Latex)
  | ({
      _key: string
    } & PullQuote)
  | ({
      _key: string
    } & Sidenote)
  | ({
      _key: string
    } & Code)
  | {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
  | ({
      _key: string
    } & External)
>

export type Company = {
  _id: string
  _type: 'company'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  company_description?: string
  logo_image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  company_page?: string
}

export type Entry = {
  _id: string
  _type: 'entry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  type?: 'essay' | 'project'
  slug?: Slug
  publishedAt?: string
  updatedAt?: string
  summary?: string
  links?: Array<{
    url?: string
    caption?: string
    _type: 'link'
    _key: string
  }>
  body?: BlockContent
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tag'
  }>
  socialImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SiteSettings
  | Sidenote
  | PullQuote
  | Latex
  | External
  | Tag
  | Tech
  | SanityImageCrop
  | SanityImageHotspot
  | Duration
  | Education
  | Experience
  | BlockContent
  | Company
  | Entry
  | Slug
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: app/(site)/experience/page.tsx
// Variable: experienceQuery
// Query: {  "featuredExperience": *[_type=="experience" && !(_id in path('drafts.**')) && featured == true]    | order(duration.start desc){      _id, role, duration, description,      "company": company->{ name, logo_image }    },  "earlierExperience": *[_type=="experience" && !(_id in path('drafts.**')) && featured != true]    | order(duration.start desc){      _id, role, duration,      "company": company->{ name, logo_image }    },  "education": *[_type=="education" && !(_id in path('drafts.**'))]    | order(year_end desc){      _id, school, degree, year_start, year_end,      "company": company->{ name, logo_image }    }}
export type ExperienceQueryResult = {
  featuredExperience: Array<{
    _id: string
    role: string | null
    duration: Duration | null
    description: BlockContent | null
    company: {
      name: string | null
      logo_image: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      } | null
    } | null
  }>
  earlierExperience: Array<{
    _id: string
    role: string | null
    duration: Duration | null
    company: {
      name: string | null
      logo_image: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      } | null
    } | null
  }>
  education: Array<{
    _id: string
    school: string | null
    degree: string | null
    year_start: number | null
    year_end: number | null
    company: {
      name: string | null
      logo_image: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      } | null
    } | null
  }>
}

// Source: app/(site)/page.tsx
// Variable: homeQuery
// Query: {  "about": *[_type=="siteSettings" && !(_id in path('drafts.**'))][0]{    name, bio, intro  }}
export type HomeQueryResult = {
  about: {
    name: string | null
    bio: string | null
    intro: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal'
      listItem?: never
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
  } | null
}

// Source: app/(site)/writing/[slug]/page.tsx
// Variable: entryDetailQuery
// Query: *[_type=="entry" && slug.current == $slug][0]{  _id, title, type, summary, publishedAt, updatedAt, links, body,  "tags": tags[]->{ name },  "prev": *[_type=="entry" && defined(slug.current) && defined(publishedAt) && publishedAt < ^.publishedAt]    | order(publishedAt desc)[0]{ title, "slug": slug.current },  "next": *[_type=="entry" && defined(slug.current) && defined(publishedAt) && publishedAt > ^.publishedAt]    | order(publishedAt asc)[0]{ title, "slug": slug.current },  "related": *[_type=="entry" && defined(slug.current) && _id != ^._id && count(tags[@._ref in ^.tags[]._ref]) > 0]    | order(publishedAt desc)[0...3]{ title, "slug": slug.current, publishedAt }}
export type EntryDetailQueryResult = {
  _id: string
  title: string | null
  type: 'essay' | 'project' | null
  summary: string | null
  publishedAt: string | null
  updatedAt: string | null
  links: Array<{
    url?: string
    caption?: string
    _type: 'link'
    _key: string
  }> | null
  body: BlockContent | null
  tags: Array<{
    name: string | null
  }> | null
  prev: {
    title: string | null
    slug: string | null
  } | null
  next: {
    title: string | null
    slug: string | null
  } | null
  related: Array<{
    title: string | null
    slug: string | null
    publishedAt: string | null
  }>
} | null
// Variable: entrySlugsQuery
// Query: *[_type=="entry" && defined(slug.current)].slug.current
export type EntrySlugsQueryResult = Array<string | null>
// Variable: entryMetaQuery
// Query: *[_type=="entry" && slug.current == $slug][0]{ title, summary, socialImage }
export type EntryMetaQueryResult = {
  title: string | null
  summary: string | null
  socialImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
} | null

// Source: app/(site)/writing/page.tsx
// Variable: writingIndexQuery
// Query: *[_type=="entry" && !(_id in path('drafts.**')) && defined(slug.current) && defined(publishedAt)]  | order(publishedAt desc){    title, "slug": slug.current, type, publishedAt, summary  }
export type WritingIndexQueryResult = Array<{
  title: string | null
  slug: string | null
  type: 'essay' | 'project' | null
  publishedAt: string | null
  summary: string | null
}>

// Source: app/feed.xml/route.ts
// Variable: feedQuery
// Query: *[_type=="entry" && !(_id in path('drafts.**')) && defined(slug.current) && defined(publishedAt)]  | order(publishedAt desc)[0...50]{    title, "slug": slug.current, summary, publishedAt, updatedAt, body  }
export type FeedQueryResult = Array<{
  title: string | null
  slug: string | null
  summary: string | null
  publishedAt: string | null
  updatedAt: string | null
  body: BlockContent | null
}>

// Source: components/site/Footer.tsx
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{ linkedinUrl, githubUrl }
export type SiteSettingsQueryResult = {
  linkedinUrl: string | null
  githubUrl: string | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '{\n  "featuredExperience": *[_type=="experience" && !(_id in path(\'drafts.**\')) && featured == true]\n    | order(duration.start desc){\n      _id, role, duration, description,\n      "company": company->{ name, logo_image }\n    },\n  "earlierExperience": *[_type=="experience" && !(_id in path(\'drafts.**\')) && featured != true]\n    | order(duration.start desc){\n      _id, role, duration,\n      "company": company->{ name, logo_image }\n    },\n  "education": *[_type=="education" && !(_id in path(\'drafts.**\'))]\n    | order(year_end desc){\n      _id, school, degree, year_start, year_end,\n      "company": company->{ name, logo_image }\n    }\n}': ExperienceQueryResult
    '{\n  "about": *[_type=="siteSettings" && !(_id in path(\'drafts.**\'))][0]{\n    name, bio, intro\n  }\n}': HomeQueryResult
    '*[_type=="entry" && slug.current == $slug][0]{\n  _id, title, type, summary, publishedAt, updatedAt, links, body,\n  "tags": tags[]->{ name },\n  "prev": *[_type=="entry" && defined(slug.current) && defined(publishedAt) && publishedAt < ^.publishedAt]\n    | order(publishedAt desc)[0]{ title, "slug": slug.current },\n  "next": *[_type=="entry" && defined(slug.current) && defined(publishedAt) && publishedAt > ^.publishedAt]\n    | order(publishedAt asc)[0]{ title, "slug": slug.current },\n  "related": *[_type=="entry" && defined(slug.current) && _id != ^._id && count(tags[@._ref in ^.tags[]._ref]) > 0]\n    | order(publishedAt desc)[0...3]{ title, "slug": slug.current, publishedAt }\n}': EntryDetailQueryResult
    '*[_type=="entry" && defined(slug.current)].slug.current': EntrySlugsQueryResult
    '*[_type=="entry" && slug.current == $slug][0]{ title, summary, socialImage }': EntryMetaQueryResult
    '*[_type=="entry" && !(_id in path(\'drafts.**\')) && defined(slug.current) && defined(publishedAt)]\n  | order(publishedAt desc){\n    title, "slug": slug.current, type, publishedAt, summary\n  }': WritingIndexQueryResult
    '*[_type=="entry" && !(_id in path(\'drafts.**\')) && defined(slug.current) && defined(publishedAt)]\n  | order(publishedAt desc)[0...50]{\n    title, "slug": slug.current, summary, publishedAt, updatedAt, body\n  }': FeedQueryResult
    '*[_type == "siteSettings"][0]{ linkedinUrl, githubUrl }': SiteSettingsQueryResult
  }
}
